# Generated by Django 5.2.14 on 2026-05-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="The employee's first or given name.", max_length=100)),
                ('last_name', models.CharField(help_text="The employee's family or legal surname.", max_length=100)),
                ('email', models.EmailField(help_text='Unique corporate email address contact.', max_length=254, unique=True)),
                ('biography', models.TextField(blank=True, help_text='Optional background notes or experience history.')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Base annual compensation amount.', max_digits=10)),
                ('role', models.CharField(choices=[('TR', 'Trainee'), ('DV', 'Developer'), ('MG', 'Manager'), ('EX', 'Executive')], default='TR', help_text='Current internal organizational position assignment.', max_length=2)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Timestamp logging when profile was created.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp auto-updating on every save operation.')),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'ordering': ['-date_joined'],
            },
        ),
    ]
